version: '2'
services:
  mariadb:
    image: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=jidahsdiasdfeweuiuanzxicvbdfias
    volumes:
      - ./conf/mariadb:/etc/mysql/conf.d
    ports:
      - "3307:3307" #mariadb-port
    container_name: mariadb

  redis-cache:
    image: redis:alpine
    volumes:
      - ./conf/redis/redis_cache.conf:/etc/conf.d/redis.conf

    command: ["redis-server","/etc/conf.d/redis.conf"]
    container_name: redis-cache

  redis-queue:
    image: redis:alpine
    volumes:
      - ./conf/redis/redis_queue.conf:/etc/conf.d/redis.conf

    command: ["redis-server","/etc/conf.d/redis.conf"]
    container_name: redis-queue

  redis-socketio:
    image: redis:alpine
    volumes:
      - ./conf/redis/redis_socketio.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    container_name: redis-socketio

  frappe:
    volumes:
    - ./bench:/app/frappe-bench
    build: .
    ports:
      - "8081:80" #webserver_port
      - "8000:8000" #webserver_port
      - "9000:9000" #socketio_port
      - "6787:6787" #file_watcher_port
    command: ['sudo', 'supervisord', '--nodaemon', '-c', '/etc/supervisor/supervisord.conf']
    stdin_open: true
    tty: true
    environment:
      - ROOT_PASSWD=jidahsdiasdfeweuiuanzxicvbdfias
      - SITE_NAME=hq.kho-gom.com
      - SITE_PORT=80

    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    container_name: frappe
