version: '3.6'
volumes:
  frappe_mariadb_data:
    external:
      name: frappe_mariadb_data
  frappe_erpnext_data:
    external:
      name: frappe_erpnext_data
services:
  mariadb:
    image: fiisoft/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=jidahsdiasdfeweuiuanzxicvbdfias
      - MYSQL_ROOT_HOST=%
    volumes:
      - frappe_mariadb_data:/var/lib/mysql
    ports:
      - "3307:3307" #mariadb-port
    container_name: mariadb
  frappe:
    volumes:
    - frappe_erpnext_data:/opt/frappe-bench/sites
    image: fiisoft/frappe
    ports:
      - "8080:80" #webserver_port
      - "8000:8000" #webserver_port
      - "9000:9000" #socketio_port
      - "6787:6787" #file_watcher_port
    environment:
      - ROOT_PASSWD=jidahsdiasdfeweuiuanzxicvbdfias
      - SITE_NAME=erp.abx-ltd.com
      - SITE_PORT=80
    links:
      - mariadb
    depends_on:
      - mariadb
    container_name: frappe
