apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  ports:
  - name: "3307"
    port: 3307
    targetPort: 3307
  selector:
    io.kompose.service: mariadb
status:
  loadBalancer: {}
