apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis-cache
  name: redis-cache
spec:
  ports:
  - name: "13000"
    port: 13000
    targetPort: 6379
  selector:
    io.kompose.service: redis-cache
status:
  loadBalancer: {}
