apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-cache
  name: redis-cache
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis-cache
    spec:
      containers:
      - args:
        - redis-server
        - /etc/conf.d/redis.conf
        image: redis:alpine
        name: redis-cache
        resources: {}
        volumeMounts:
        - mountPath: /etc/conf.d/redis.conf
          name: redis-cache-claim0
      restartPolicy: Always
      volumes:
      - name: redis-cache-claim0
        persistentVolumeClaim:
          claimName: redis-cache-claim0
status: {}
