apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis-queue
  name: redis-queue
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis-queue
    spec:
      containers:
      - image: redis:alpine
        name: redis-queue
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}
