apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis-socketio
  name: redis-socketio
spec:
  ports:
  - name: "12000"
    port: 12000
    targetPort: 6379
  selector:
    io.kompose.service: redis-socketio
status:
  loadBalancer: {}
