#!/bin/bash
if [[ -z "$SITE_NAME" ]] || [[ -z "$SITE_PORT" ]]
then
    echo "SITE_NAME & SITE_PORT is not defined" && exit 1
fi

SITE_LOCK=/app/frappe-volume/site_$SITE_NAME
PORT_LOCK=/app/frappe-volume/site_$PORT_NAME

if [ -f $SITE_LOCK  ]; then
    echo "Site ${SITE_NAME} is already setup!" && exit 1
fi

if [ -f $PORT_LOCK ]; then
    echo "Port ${SITE_PORT} is already registered!" && exit 1
fi

cd /app/frappe-bench

bench new-site $SITE_NAME
bench --site $SITE_NAME install-app bench_manager
bench --site $SITE_NAME install-app erpnext
bench set-nginx-port $SITE_NAME $SITE_PORT
bench setup nginx --yes

date > $SITE_LOCK
date > $PORT_LOCK
