#!/bin/bash

BENCH_LOCK=/app/frappe-bench/.bench_setup

if [ -f $BENCH_LOCK  ]; then
    echo "Site ${BENCH_LOCK} is already setup!"
else
    cd /app
    rsync -av --ignore-existing /app/frappe-init/ /app/frappe-bench/
    bench init frappe-bench --skip-bench-mkdir --skip-redis-config-generation

    cd /app/frappe-bench
    bench get-app bench_manager https://github.com/frappe/bench_manager
    bench get-app erpnext https://github.com/frappe/erpnext
    bench setup supervisor --user frappe --yes
    cat /app/frappe-bench/config/supervisor.conf

    ln -sf /app/frappe-bench/config/supervisord.conf /etc/supervisor/conf.d/frappe-bench.conf
    ln -sf /app/frappe-bench/config/nginx.conf /etc/nginx/sites-enabled/frappe-sites.conf
fi

cd /app/frappe-bench
[[ ! -z "$REDIS_CACHE" ]] && bench config set-common-config -c "redis_cache" "$REDIS_CACHE" && echo Set config REDIS_CACHE
[[ ! -z "$REDIS_QUEUE" ]] && bench config set-common-config -c "redis_queue" "$REDIS_QUEUE" && echo Set config REDIS_QUEUE
[[ ! -z "$REDIS_SOCKETIO" ]] && bench config set-common-config -c "redis_socketio" "$REDIS_SOCKETIO" && echo Set config REDIS_SOCKETIO
[[ ! -z "$ROOT_PASSWD" ]] && bench config set-common-config -c "root_password" "$ROOT_PASSWD" && echo Set config ROOT_PASSWD
[[ ! -z "$MARIADB_HOST" ]] && bench set-mariadb-host $MARIADB_HOST && echo Set config MARIADB_HOST

