#!/bin/bash

[[ ! -z "$REDIS_CACHE" ]] && bench config set-common-config -c "redis_cache" "$REDIS_CACHE" && echo Set config REDIS_CACHE
[[ ! -z "$REDIS_QUEUE" ]] && bench config set-common-config -c "redis_queue" "$REDIS_QUEUE" && echo Set config REDIS_QUEUE
[[ ! -z "$REDIS_SOCKETIO" ]] && bench config set-common-config -c "redis_socketio" "$REDIS_SOCKETIO" && echo Set config REDIS_SOCKETIO
[[ ! -z "$ROOT_PASSWD" ]] && bench config set-common-config -c "root_password" "$ROOT_PASSWD" && echo Set config ROOT_PASSWD
[[ ! -z "$MARIADB_HOST" ]] && bench set-mariadb-host $MARIADB_HOST && echo Set config MARIADB_HOST